doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                logging: true
            readonly:
                url: '%env(resolve:READONLY_DATABASE_URL)%'
                logging: true

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

                dql:
                    datetime_functions:
                        date: Oro\ORM\Query\AST\Functions\SimpleFunction
            readonly:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: readonly
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

                dql:
                    datetime_functions:
                        date: Oro\ORM\Query\AST\Functions\SimpleFunction
