version: "3"

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/project/src
      - ./config:/var/www/project/config
      - ./public:/var/www/project/public
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379"
