monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_http_codes: [404, 405]
        grouped:
            type: group
            members: [ nested, deduplicated ]
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
            max_files: 7
        deduplicated:
            type: deduplication
            action_level: critical
            handler: swift
        swift:
            type: swift_mailer
            from_email: 'api@poppyseedpets.com'
            to_email: 'ben@poppyseedpets.com'
            subject: "Poppy Seed Pets Exception: %%message%%"
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
