version: "3"

services:
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/project/public
  php:
    image: php:8.1-fpm
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/project/src
      - ./config:/var/www/project/config
      - ./public:/var/www/project/public
