# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    adminIpRegex: '%env(ADMIN_IP_REGEX)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\PetActivity\:
        resource: '../src/Service/PetActivity'
        lazy: true

    App\Service\Holidays\:
        resource: '../src/Service/Holidays'
        lazy: true

    App\Service\TwitterService:
        arguments:
            $apiConsumerKey: '%env(TWITTER_API_CONSUMER_KEY)%'
            $apiConsumerSecret: '%env(TWITTER_API_CONSUMER_SECRET)%'
            $apiAccessToken: '%env(TWITTER_API_ACCESS_TOKEN)%'
            $apiAccessTokenSecret: '%env(TWITTER_API_ACCESS_SECRET)%'

    App\Service\RedditService:
        arguments:
            $apiClientId: '%env(REDDIT_API_CLIENT_ID)%'
            $apiClientSecret: '%env(REDDIT_API_CLIENT_SECRET)%'
            $username: '%env(REDDIT_API_USERNAME)%'
            $password: '%env(REDDIT_API_PASSWORD)%'
