/*
 * This file is part of the Poppy Seed Pets Webapp.
 *
 * The Poppy Seed Pets Webapp is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * The Poppy Seed Pets Webapp is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with The Poppy Seed Pets Webapp. If not, see <https://www.gnu.org/licenses/>.
 */
const META_ACHIEVEMENT_BACKGROUND = 'conic-gradient(from 90deg at 25% -10%, #ff4500, #d3f340, #7bee85, #afeeee, #7bee85)';
const RECYCLING_BACKGROUND = 'conic-gradient(from 90deg at 50% 110%, #1f005c, #003298, #005ac6, #007fdc, #00a2d3, #00c4ae, #00e474, #00ff00, #1f005c, #003298, #005ac6, #007fdc, #00a2d3, #00c4ae, #00e474, #00ff00)';
const BUG_BACKGROUND = 'conic-gradient(from 90deg at 50% 110%, #ff9a0f, #ff9a0f, #ff9a0f, #ff9a0f, #dee900, #00c409)';

const ZOOLOGIST_BRONZE_BACKGROUND = 'linear-gradient(120deg, #ff8812, #a65300)';
const ZOOLOGIST_SILVER_BACKGROUND = 'linear-gradient(120deg, #ddeeff, #7c7c7c)';
const ZOOLOGIST_GOLD_BACKGROUND = 'linear-gradient(120deg, #f9ff67, #daad22)';

const MUSEUM_BRONZE_BACKGROUND = 'conic-gradient(from -90deg at 50% -10%, #ff8812, #a65300, #ff8812, #a65300, #ff8812, #a65300, #ff8812, #a65300)';
const MUSEUM_SILVER_BACKGROUND = 'conic-gradient(from -90deg at 50% -10%, #ddeeff, #7c7c7c, #ddeeff, #7c7c7c, #ddeeff, #7c7c7c, #ddeeff, #7c7c7c)';
const MUSEUM_GOLD_BACKGROUND = 'conic-gradient(from -90deg at 50% -10%, #f9ff67, #daad22, #f9ff67, #daad22, #f9ff67, #daad22, #f9ff67, #daad22)';

export interface BadgeInfo {
  title: string;
  description: string;
  image: string;
  color: string;
  group: string;
  order: number;
}

export const BADGE_GROUP_ICONS: { [key:string]: string } = {
  'Recycling': 'fa-solid fa-leaf',
  'Pet Care': 'fa-solid fa-paw',
  'Food & Cooking': 'fa-solid fa-utensils',
  'Bugs': 'fa-solid fa-bug',
  'Fireplace': 'fa-solid fa-fire',
  'Greenhouse': 'fa-solid fa-seedling',
  'Treasure': 'fa-solid fa-gem',
  'Love of Boxes': 'fa-solid fa-box-open',
  'Adventure': 'fa-solid fa-swords',
  'Great Spirits': 'fa-solid fa-pegasus',
  'Events': 'fa-solid fa-calendar-star',
  'Getting Meta': 'fa-solid fa-award',
  'Cataloging': 'fa-solid fa-book',
};

export const BADGE_INFO: { [key:string]: BadgeInfo } = {

  // Recycling

  'Recycled10': {
    title: 'Reduce',
    description: 'Recycle 10 items.',
    image: 'items/resource/paper',
    color: RECYCLING_BACKGROUND,
    group: 'Recycling',
    order: 100,
  },
  'Recycled100': {
    title: 'Reuse',
    description: 'Recycle 100 items.',
    image: 'items/tool/basket/plastic-large',
    color: RECYCLING_BACKGROUND,
    group: 'Recycling',
    order: 101,
  },
  'Recycled1000': {
    title: 'Recycle',
    description: 'Recycle 1,000 items...',
    image: 'items/tool/shovel/plastic',
    color: RECYCLING_BACKGROUND,
    group: 'Recycling',
    order: 102,
  },
  'Recycled10000': {
    title: 'Actually Hold Companies Accountable...',
    description: 'Recycle 10,000 items!',
    image: 'items/treasure/idol-quote-gold-unquote',
    color: RECYCLING_BACKGROUND,
    group: 'Recycling',
    order: 103,
  },
  'BaabblesOpened1': {
    title: 'Goodies!',
    description: 'Open a Baabble.',
    image: 'plants/adult-goat',
    color: 'linear-gradient(-225deg, #5D9FFF 0%, #B8DCFF 48%, #6BBBFF 100%)',
    group: 'Recycling',
    order: 104,
  },
  'BaabblesOpened10': {
    title: 'MOAR GOODIES!',
    description: 'Open 10 Baabbles.',
    image: 'plants/adult-goat',
    color: 'linear-gradient(-225deg, #69EACB 0%, #EACCF8 48%, #6654F1 100%)',
    group: 'Recycling',
    order: 105,
  },
  'BaabblesOpened100': {
    title: '*bleats*',
    description: 'Open 100 Baabbles...',
    image: 'plants/fruiting-goat',
    color: 'linear-gradient(to bottom, #05f1ff 75%, #2fc529 75%)',
    group: 'Recycling',
    order: 106,
  },
  'BaabblesOpened1000': {
    title: 'Patron of the Cosmic Goat',
    description: 'Open 1,000 Baabbles!',
    image: 'plants/adult-goat',
    color: 'linear-gradient(217deg, rgba(255,0,0,.8), rgba(255,0,0,0) 70.71%), ' +
      'linear-gradient(127deg, rgba(0,255,0,.8), rgba(0,255,0,0) 70.71%), ' +
      'linear-gradient(336deg, rgba(0,0,255,.8), rgba(0,0,255,0) 70.71%)',
    group: 'Recycling',
    order: 107,
  },
  'WeekdayCoins1': {
    title: '7 Days a Week...',
    description: 'Make a trade for Kat\'s Gift Package.',
    image: 'items/coin/frigga',
    color: 'conic-gradient(pink, yellow, cyan, pink)',
    group: 'Recycling',
    order: 108,
  },
  'WeekdayCoins7': {
    title: '... for 7 Weeks',
    description: 'Make 7 trades for Kat\'s Gift Package.',
    image: 'items/coin/sun',
    color: 'conic-gradient(pink, yellow, cyan, pink)',
    group: 'Recycling',
    order: 108,
  },

  // Pets

  'Petted10': {
    title: 'Fam Fan',
    description: '"Do quality time!" totalling 10 pets.',
    image: 'items/mineral/heart',
    color: 'linear-gradient(122.3deg, #fddb92 0%, #d1fdff 100%)',
    group: 'Pet Care',
    order: 200,
  },
  'Petted100': {
    title: 'Clan Stan',
    description: '"Do quality time!" totalling 100 pets.',
    image: 'items/resource/fluff-heart',
    color: 'linear-gradient(302.3deg, #fddb92 0%, #d1fdff 100%)',
    group: 'Pet Care',
    order: 201,
  },
  'Petted1000': {
    title: 'Flimflam?',
    description: '"Do quality time!" totalling 1,000 pets....',
    image: 'items/hat/top-hat-heart',
    color: 'linear-gradient(122.3deg, #b8cbb8 0%, #b8cbb8 0%, #b465da 0%, #cf6cc9 33%, #ee609c 66%, #ee609c 100%)',
    group: 'Pet Care',
    order: 202,
  },
  'Petted10000': {
    title: '<3',
    description: '"Do quality time!" totalling 10,000 pets!',
    image: 'items/element/heartessence',
    color: 'linear-gradient(122.3deg, rgba(111,71,133,1) 14.6%, rgba(232,129,166,1) 29.6%, rgba(237,237,183,1) 42.1%, rgba(244,166,215,1) 56.7%, rgba(154,219,232,1) 68.7%, rgba(238,226,159,1) 84.8%)',
    group: 'Pet Care',
    order: 203,
  },
  'HeartstoneDimensionCompleted': {
    title: 'Know Thyself',
    description: 'Have a pet fully explore the Crystal Heart Dimension.',
    image: 'icons/activity-logs/heart-dimension',
    color: 'conic-gradient(from 112.5deg, #fff0, #0003, #fff0, #fff3, #fff0, #0003, #fff0, #fff3, #fff0),' +
      'radial-gradient(circle, #000000 25%, #ae008d 100%)',
    group: 'Pet Care',
    order: 203.5,
  },
  'MaxPets4': {
    title: 'M-M-M-MAXIMUM PETS',
    description: 'Have a house that can support up to 4 pets.',
    image: 'pets/monotreme/desikh',
    color: '#ffffff',
    group: 'Pet Care',
    order: 204,
  },
  'TrophiesEarned1': {
    title: 'Backyard Sportsball Player',
    description: 'Win a Trophy in a park event.',
    image: 'items/tool/sportsball/green',
    color: 'linear-gradient(to bottom, #83B3FF 0%, #90FF94 100%)',
    group: 'Pet Care',
    order: 204.1,
  },
  'TrophiesEarned10': {
    title: 'Good at Sports',
    description: 'Win 10 Trophies in park events...',
    image: 'items/trophy/tri-d-chess-silver',
    color: 'linear-gradient(to bottom, #83B3FF 0%, #90FF94 100%)',
    group: 'Pet Care',
    order: 204.2,
  },
  'TrophiesEarned100': {
    title: 'Sports Legend',
    description: 'Win 100 Trophies in park events!',
    image: 'items/trophy/jousting-gold',
    color: 'linear-gradient(to bottom, #83B3FF 0%, #90FF94 100%)',
    group: 'Pet Care',
    order: 204.3,
  },
  'OpenedHatBox1': {
    title: 'Looks Good on You',
    description: 'Open a Hat Box.',
    image: 'items/hat/top-hat-eccentric',
    color: 'radial-gradient(circle 703px at 87.3% 129.3%, rgba(240,70,119,1) 21.4%, rgba(255,160,128,1) 50.4%, rgba(255,255,255,1) 100.2%)',
    group: 'Pet Care',
    order: 205,
  },
  'OpenedHatBox10': {
    title: 'Like a Box of Chocolates, but for Hats',
    description: 'Open 10 Hat Boxes.',
    image: 'items/hat/top-hat-eccentric',
    color: 'radial-gradient(circle farthest-corner at 10% 20%, rgba(147,67,67,1) 0%, rgba(111,27,27,1) 90%)',
    group: 'Pet Care',
    order: 206,
  },
  'UnlockedHattierStyles10': {
    title: 'Styles Upon Styles',
    description: 'Unlock 10 Styles at the Hattier.',
    image: 'auras/glitter',
    color: '#111111',
    group: 'Pet Care',
    order: 207,
  },
  'UnlockedHattierStyles20': {
    title: 'Rockin\' That Noggin',
    description: 'Unlock 20 Styles at the Hattier.',
    image: 'pets/elemental/head',
    color: 'radial-gradient(circle farthest-corner at 50% 80%, #ffffff 0%, #9cdda1 90%)',
    group: 'Pet Care',
    order: 208,
  },
  'UnlockedHattierStyles30': {
    title: 'Unparalleled Elegance',
    description: 'Unlock 30 Styles at the Hattier.',
    image: 'auras/diamonds',
    color: 'linear-gradient(to bottom, #0fffea 0%, #d22aff 100%)',
    group: 'Pet Care',
    order: 209,
  },
  'DragonVaseDipping10': {
    title: 'What\'s in That Vase, Even?',
    description: 'Make 10 tools more-better using a Dragon Vase',
    image: 'items/treasure/vase-dragon',
    color: 'linear-gradient(to bottom, #eee 0%, #fff 75%, orange 75%)',
    group: 'Pet Care',
    order: 210,
  },

  // Food & Cooking

  'Cooked10': {
    title: 'Line Cook',
    description: 'Prepare 10 recipes.',
    image: 'items/animal/egg-fried',
    color: 'radial-gradient(64px, rgba(255, 255, 249, 1) 0%, rgb(160, 199, 254) 74.6%)',
    group: 'Food & Cooking',
    order: 300,
  },
  'Cooked100': {
    title: 'Commis Chef',
    description: 'Prepare 100 recipes.',
    image: 'items/wine/blood',
    color: 'radial-gradient(64px, rgba(255, 255, 249, 1) 0%, rgb(160, 199, 254) 74.6%)',
    group: 'Food & Cooking',
    order: 301,
  },
  'Cooked1000': {
    title: 'Sous Chef',
    description: 'Prepare 1,000 recipes...',
    image: 'items/soup/fishkebab',
    color: 'radial-gradient(64px, rgba(255, 255, 249, 1) 0%, rgb(160, 199, 254) 74.6%)',
    group: 'Food & Cooking',
    order: 302,
  },
  'Cooked10000': {
    title: 'Master Chef',
    description: 'Prepare 10,000 recipes!',
    image: 'items/dessert/pie-slice-all-flavor',
    color: 'radial-gradient(64px, rgba(255, 255, 249, 1) 0%, rgb(160, 199, 254) 74.6%)',
    group: 'Food & Cooking',
    order: 303,
  },
  'SouffleStartler': {
    title: 'But Why?',
    description: 'Startle a Soufflé.',
    image: 'items/frittata/souffle-startled',
    color: 'linear-gradient(to bottom, palegoldenrod 62%, #9e6921 62%)',
    group: 'Food & Cooking',
    order: 304,
  },
  'WhisperStone': {
    title: 'Earthly Knowledge',
    description: 'Listen to a Whisper Stone.',
    image: 'items/mineral/striped-whisper',
    color: 'linear-gradient(to top, #dbdcd7 0%, #dddcd7 24%, #e2c9cc 30%, #e7627d 46%, #b8235a 59%, #801357 71%, #3d1635 84%, #1c1a27 100%)',
    group: 'Food & Cooking',
    order: 305,
  },
  'OpenedCanOfFood10': {
    title: 'Surprisingly Uncommon',
    description: 'Open 10 Canned Foods.',
    image: 'items/tool/scissors/yellow-can-opener',
    color: '#778',
    group: 'Food & Cooking',
    order: 306,
  },
  'OpenedCanOfFood100': {
    title: 'Wretched Worms!',
    description: 'Open 100 Canned Foods.',
    image: 'items/tool/scissors/green-can-opener',
    color: '#f69',
    group: 'Food & Cooking',
    order: 307,
  },
  'OpenedPaperBag10': {
    title: 'Surprisingly Common',
    description: 'Open 10 Paper Bags.',
    image: 'items/bag/paper',
    color: '#778',
    group: 'Food & Cooking',
    order: 308,
  },
  'OpenedPaperBag100': {
    title: 'Cursed Cockroaches!',
    description: 'Open 100 Paper Bags.',
    image: 'items/bag/paper',
    color: '#963',
    group: 'Food & Cooking',
    order: 309,
  },
  'OpenedPlasticBottle10': {
    title: 'Surprisingly Strong',
    description: 'Open 10 Plastic Bottles.',
    image: 'items/box/bottle',
    color: 'radial-gradient(#ccf 0%, #fff 80%)',
    group: 'Food & Cooking',
    order: 310,
  },
  'OpenedPlasticBottle100': {
    title: 'Unfortunately Common',
    description: 'Open 100 Plastic Bottles.',
    image: 'items/box/bottle',
    color: 'radial-gradient(#d60 0%, #ff0 85%)',
    group: 'Food & Cooking',
    order: 311,
  },
  'OpenedCerealBox': {
    title: 'Magically Delicious',
    description: 'Open a Cereal Box.',
    image: 'visiting-birds/toucan',
    color: 'conic-gradient(from 45deg, cyan, magenta, yellow, cyan)',
    group: 'Food & Cooking',
    order: 312,
  },
  'OpenedCerealBoxCanOfFoodPaperBag100': {
    title: 'Lucky Charm',
    description: 'Open a Cereal Box, 100 Canned Foods, and 100 Paper Bags!',
    image: 'items/hat/rainbow',
    color: '#befff1',
    group: 'Food & Cooking',
    order: 313,
  },
  'HotPotDipping10': {
    title: 'Shabu Shabu, My Friend',
    description: 'Spice 10 foods using a Hot Pot.',
    image: 'items/treasure/hot-pot',
    color: '#ffffff',
    group: 'Food & Cooking',
    order: 314,
  },
  'HotPotatoTossed1': {
    title: 'Tater Toter',
    description: 'Toss a Hot Potato.',
    image: 'items/veggie/potato-hot',
    color: 'linear-gradient(-45deg, rgb(87, 172, 48) 50%, rgb(166, 223, 98) 50%)',
    group: 'Food & Cooking',
    order: 315,
  },
  'HotPotatoTossed10': {
    title: 'Tater Tosser',
    description: 'Toss 10 Hot Potatoes...',
    image: 'items/veggie/potato-hot',
    color: 'linear-gradient(-45deg, rgb(255, 160, 0) 50%, rgb(87, 172, 48) 50%)',
    group: 'Food & Cooking',
    order: 316,
  },
  'HotPotatoTossed100': {
    title: 'Tater Terrorizer',
    description: 'Toss 100 Hot Potatoes! <small>(Sorry about all the Potatoes...)</small>',
    image: 'items/veggie/potato-hot',
    color: 'linear-gradient(-45deg, rgb(255, 80, 0) 50%, rgb(255, 160, 0) 50%)',
    group: 'Food & Cooking',
    order: 317,
  },
  'CookingBuddyRecipes100': {
    title: 'Cooking Passing Acquaintance',
    description: 'Teach your Cooking Buddy 100 recipes.',
    image: 'items/robot/cooking',
    color: 'linear-gradient(to bottom, #ffffff 75%, #9e6921 75%)',
    group: 'Food & Cooking',
    order: 318,
  },
  'CookingBuddyRecipes200': {
    title: 'Cooking Friend of a Friend',
    description: 'Teach your Cooking Buddy 200 recipes.',
    image: 'items/robot/cooking',
    color: 'linear-gradient(to bottom, #9edbf4 75%, #9e6921 75%)',
    group: 'Food & Cooking',
    order: 319,
  },
  'CookingBuddyRecipes300': {
    title: 'Cooking Buddy',
    description: 'Teach your Cooking Buddy 300 recipes.',
    image: 'items/robot/cooking',
    color: 'linear-gradient(to bottom, #f4e39e 75%, #9e6921 75%)',
    group: 'Food & Cooking',
    order: 320,
  },
  'CookingBuddyRecipes400': {
    title: 'Cooking BFF',
    description: 'Teach your Cooking Buddy 400 recipes.',
    image: 'items/robot/cooking',
    color: 'linear-gradient(to bottom, #dda7f8 75%, #9e6921 75%)',
    group: 'Food & Cooking',
    order: 321,
  },
  'CookingBuddyRecipes500': {
    title: 'Cooking FWB',
    description: 'Teach your Cooking Buddy 500 recipes.',
    image: 'items/robot/cooking',
    color: 'linear-gradient(to bottom, #f8a7a7 75%, #9e6921 75%)',
    group: 'Food & Cooking',
    order: 322,
  },
  'CookingBuddyRecipes600': {
    title: 'Cooking Life Partner',
    description: 'Teach your Cooking Buddy 600 recipes.',
    image: 'items/robot/cooking',
    color: 'linear-gradient(to bottom, #a7f8b0 75%, #9e6921 75%)',
    group: 'Food & Cooking',
    order: 323,
  },
  'CookingBuddyRecipes700': {
    title: 'Cooking... Cooking! Cooking-cooking!',
    description: 'Teach your Cooking Buddy 700 recipes.',
    image: 'items/robot/cooking',
    color: 'linear-gradient(to bottom, #f5f5f5 75%, #9e6921 75%)',
    group: 'Food & Cooking',
    order: 324,
  },

  // Bugs

  'FedCentipedes10': {
    title: 'Definitely How Evolution Works',
    description: 'Cause 10 Centipedes to "evolve".',
    image: 'items/bug/moth',
    color: BUG_BACKGROUND,
    group: 'Bugs',
    order: 350,
  },
  'FedAnts10': {
    title: 'Friend of Ants',
    description: 'Feed a Line of Ants 10 times.',
    image: 'items/bug/ant-queen',
    color: BUG_BACKGROUND,
    group: 'Bugs',
    order: 351,
  },
  'FedBees10': {
    title: 'Friend of Bees',
    description: 'Give your bee queen what she wants... 10 times.',
    image: 'items/bug/bee',
    color: BUG_BACKGROUND,
    group: 'Bugs',
    order: 352,
  },
  'FedAntsAndBees10': {
    title: 'Playing Both Sides',
    description: 'Get the "Friend of Ants" and "Friend of Bees" Achievements.',
    image: 'items/hat/dicerca',
    color: BUG_BACKGROUND,
    group: 'Bugs',
    order: 353
  },
  'WorkerBees1000': {
    title: 'Buzz Buzz',
    description: 'Have a hive with 1,000 worker bees.',
    image: 'items/bug/bee',
    color: 'skyblue',
    group: 'Bugs',
    order: 354,
  },
  'WorkerBees10000': {
    title: 'Very Buzz Buzz',
    description: 'Have a hive with 10,000 worker bees.',
    image: 'items/bug/bee',
    color: 'conic-gradient(from 112.5deg, #fff, skyblue, #fff, skyblue, #fff, skyblue, #fff, skyblue, #fff)',
    group: 'Bugs',
    order: 355,
  },

  // Fireplace

  'LongestFire60': {
    title: 'Fleeting Warmth',
    description: 'Have a fire burning for 1 contiguous hour.',
    image: 'items/trinket/hourglass',
    color: 'linear-gradient(to right, #581f1f 50%, #c85555 50%)',
    group: 'Fireplace',
    order: 400,
  },
  'LongestFire1440': {
    title: 'Hot Cocoa Day',
    description: 'Have a fire burning for 1 contiguous day.',
    image: 'items/trinket/hourglass',
    color: 'linear-gradient(to right, #c85555 50%, #e2e126 50%)',
    group: 'Fireplace',
    order: 401,
  },
  'LongestFire10080': {
    title: 'Toas-ty!',
    description: 'Have a fire burning for 1 contiguous week.',
    image: 'items/trinket/hourglass',
    color: 'linear-gradient(to right, #e2e126 50%, #ffffff 50%)',
    group: 'Fireplace',
    order: 402,
  },
  'FireplaceFuel10': {
    title: 'L\'il Pyro',
    description: 'Toss 10 items into your Fireplace.',
    image: 'icons/activity-logs/burn',
    color: '#222222',
    group: 'Fireplace',
    order: 403,
  },
  'FireplaceFuel100': {
    title: 'Some People...',
    description: 'Toss 100 items into your Fireplace.',
    image: 'icons/activity-logs/burn',
    color: '#7d2727',
    group: 'Fireplace',
    order: 404,
  },
  'FireplaceFuel1000': {
    title: 'Nero',
    description: 'Toss 1,000 items into your Fireplace...',
    image: 'icons/activity-logs/burn',
    color: '#e19e2b',
    group: 'Fireplace',
    order: 405,
  },
  'FireplaceFuel10000': {
    title: 'The Burninator',
    description: 'Toss 10,000 items into your Fireplace!',
    image: 'icons/activity-logs/burn',
    color: '#fffa9a',
    group: 'Fireplace',
    order: 406,
  },


  // Greenhouse

  'FertilizedPlant10': {
    title: 'No Thumb',
    description: 'Fertilize 10 plants.',
    image: 'plants/medium-bean-stalk',
    color: 'linear-gradient(to bottom, #05f1ff 75%, #2fc529 75%)',
    group: 'Greenhouse',
    order: 450,
  },
  'FertilizedPlant100': {
    title: 'Green Thumb',
    description: 'Fertilize 100 plants...',
    image: 'plants/adult-magic-bean',
    color: 'linear-gradient(to bottom, #05f1ff 75%, #2fc529 75%)',
    group: 'Greenhouse',
    order: 451,
  },
  'FertilizedPlant1000': {
    title: 'Purple Thumb',
    description: 'Fertilize 1,000 plants!',
    image: 'plants/fruiting-magic-bean',
    color: 'linear-gradient(to bottom, #05f1ff 75%, #2fc529 75%)',
    group: 'Greenhouse',
    order: 452,
  },
  'HarvestedPlant10': {
    title: 'Photosynthesizer!',
    description: 'Harvest 10 plants.',
    image: 'items/box/fruit-basket',
    color: 'radial-gradient(circle 763px at 18.3% 24.1%, rgba(255,249,137,1) 7.4%, rgba(226,183,40,1) 58.3%)',
    group: 'Greenhouse',
    order: 453,
  },
  'HarvestedPlant100': {
    title: 'Stomatal Regulator!!',
    description: 'Harvest 100 plants...',
    image: 'items/box/fruit-basket',
    color: 'radial-gradient(circle farthest-corner at 10% 20%, rgba(161,255,255,1) 11.3%, rgba(6,255,255,1) 41.2%, rgba(0,216,216,1) 77.8%)',
    group: 'Greenhouse',
    order: 454,
  },
  'HarvestedPlant1000': {
    title: 'Mychorrhizal Associator???',
    description: 'Harvest 1,000 plants!',
    image: 'items/box/fruit-basket',
    color: 'radial-gradient(circle farthest-corner at 10% 20%, rgba(62,133,238,1) 1.1%, rgba(227,137,240,1) 43.7%, rgba(243,193,124,1) 89.7%)',
    group: 'Greenhouse',
    order: 455,
  },
  'Composted10': {
    title: 'Small Bag of Poop',
    description: 'Compost 10 items.',
    image: 'items/fertilizer/small',
    color: 'linear-gradient(57deg, #bd6042 0%, #e6c78b 100%)',
    group: 'Greenhouse',
    order: 456,
  },
  'Composted100': {
    title: 'Bag of Poop',
    description: 'Compost 100 items...',
    image: 'items/fertilizer/medium',
    color: 'linear-gradient(57deg, #bd6042 0%, #e6c78b 100%)',
    group: 'Greenhouse',
    order: 457,
  },
  'Composted1000': {
    title: 'Large Bag of Poop',
    description: 'Compost 1,000 items!',
    image: 'items/fertilizer/large',
    color: 'linear-gradient(57deg, #bd6042 0%, #e6c78b 100%)',
    group: 'Greenhouse',
    order: 458,
  },
  'FertilizedHarvestedComposted1000': {
    title: 'Master Gardener',
    description: 'Get the "Purple Thumb", "Mychorrhizal Associator???", and "Large Bag of Poop" Achievements.',
    image: 'plants/fruiting-chanterelle',
    color: 'linear-gradient(180deg, #43da89 0%, #a6f997 100%)',
    group: 'Greenhouse',
    order: 459,
  },
  'HorribleEggplant1': {
    title: 'Cursed Fruit',
    description: 'Clean an Eggplant and find nothing but disappointment inside.',
    image: 'items/fruit/eggplant',
    color: '#2B86C5',
    group: 'Greenhouse',
    order: 460,
  },
  'HorribleEggplant10': {
    title: 'Very Cursed Fruit',
    description: 'Clean an Eggplant and find nothing but disappointment inside... ten times!',
    image: 'items/fruit/eggplant',
    color: 'linear-gradient(225deg, #FF3CAC 0%, #784BA0 50%, #2B86C5 100%)',
    group: 'Greenhouse',
    order: 461,
  },

  // Treasure

  'MoneysSpent10': {
    title: 'Mmmmmmmmmm',
    description: 'Spend 10 Moneys.',
    image: 'auras/moneys',
    color: 'linear-gradient(to top, #daf9fa 0%, #ffffff 50%)',
    group: 'Treasure',
    order: 500,
  },
  'MoneysSpent100': {
    title: 'Mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm',
    description: 'Spend as many Moneys as there are "m"s in this Achievement\'s name. <small>(Spoilers: it\'s 100. The answer is 100.)</small>',
    image: 'auras/moneys',
    color: 'linear-gradient(to top, #dafadc 0%, #ffffff 100%)',
    group: 'Treasure',
    order: 501,
  },
  'MoneysSpent1000': {
    title: 'Goodness!',
    description: 'Spend 1,000 Moneys... <small>(1,000 "m"s would have simply been too many...)</small>',
    image: 'auras/moneys',
    color: 'linear-gradient(to top, #f4f5bf 0%, #ffffff 100%)',
    group: 'Treasure',
    order: 502,
  },
  'MoneysSpent10000': {
    title: 'Dang!',
    description: 'Spend 10,000 Moneys!',
    image: 'auras/moneys',
    color: 'linear-gradient(to top, #fbd9d9 0%, #ffffff 100%)',
    group: 'Treasure',
    order: 503,
  },
  'MoneysSpent100000': {
    title: 'Wowzers!',
    description: 'Spend 100,000 Moneys!?!!',
    image: 'auras/moneys',
    color: 'linear-gradient(to top, #fbd9fa 0%, #ffffff 100%)',
    group: 'Treasure',
    order: 504,
  },
  'TreasuresGivenToDragon10': {
    title: 'You Didn\'t Need That Stuff, Anyway',
    description: 'Give 10 treasures to your Dragon.',
    image: 'items/treasure/dragon-ingot',
    color: 'linear-gradient(135deg, #feff58 0%, #00eeeb 50%, #FFFFFF 100%)',
    group: 'Treasure',
    order: 506,
  },
  'TreasuresGivenToDragon100': {
    title: 'How to Raise a Dragon',
    description: 'Give 100 treasures to your Dragon...',
    image: 'items/treasure/dragon-ingot',
    color: 'linear-gradient(135deg, #00eeeb 0%, #FFFFFF 50%, #ffb50f 100%)',
    group: 'Treasure',
    order: 507,
  },
  'TreasuresGivenToDragon1000': {
    title: 'Even a Wealthy Scottish Duck Would Be Jealous',
    description: 'Give 1,000 treasures to your Dragon!',
    image: 'items/treasure/dragon-ingot',
    color: 'linear-gradient(135deg, #FFFFFF 0%, #ffb50f 50%, #da0000 100%)',
    group: 'Treasure',
    order: 508,
  },

  'BasementSize2000': {
    title: 'Expanding Underground',
    description: 'Reach a basement size of 2,000.',
    image: 'player-badges/basement',
    color: 'linear-gradient(to bottom, #9cf, #888)',
    group: 'Treasure',
    order: 509,
  },
  'BasementSize5000': {
    title: 'Subterranean Estate',
    description: 'Reach a basement size of 5,000...',
    image: 'player-badges/basement',
    color: 'linear-gradient(to bottom, #888, #333)',
    group: 'Treasure',
    order: 510,
  },
  'BasementSize10000': {
    title: 'Here There Be Dragons',
    description: 'Reach the maximum basement size of 10,000!',
    image: 'player-badges/basement',
    color: 'linear-gradient(to bottom, #333, #000)',
    group: 'Treasure',
    order: 511,
  },

  'OpenedInfinityVault1': {
    title: 'The Infinity Vault',
    description: 'Open the Infinity Vault.',
    image: 'player-badges/infinity-vault',
    color: 'conic-gradient(from 90deg at 50% 40%, #7b2ff7, #00c9ff, #f0f, #ff0, #7b2ff7)',
    group: 'Treasure',
    order: 512,
  },
  'InfinityVaultMoneysSpent9999': {
    title: 'Can\'t Be Bothered to Count Anymore',
    description: 'Spend 9,999 Moneys opening the Infinity Vault.',
    image: 'player-badges/infinity-vault-2',
    color: 'conic-gradient(from 90deg at 50% 40%, #ffd700, #ff8c00, #ff0, #ffd700)',
    group: 'Treasure',
    order: 513,
  },
  'MisreadScroll1': {
    title: 'Gross',
    description: 'Misread a scroll.',
    image: 'items/scroll/fruit',
    color: '#ffffff',
    group: 'Treasure',
    order: 514,
  },
  'ReadScroll1': {
    title: 'Initiate',
    description: 'Read a scroll.',
    image: 'items/hat/wizard',
    color: 'linear-gradient(90deg, rgba(243, 245, 245,0.5) 0%, rgba(243, 245, 245,0.5) 6%,transparent 6%, transparent 17%,rgba(209, 236, 244,0.5) 17%, rgba(209, 236, 244,0.5) 29%,rgba(39, 189, 241,0.5) 29%, rgba(39, 189, 241,0.5) 33%,transparent 33%, transparent 57%,rgba(175, 226, 244,0.5) 57%, rgba(175, 226, 244,0.5) 70%,rgba(107, 208, 242,0.5) 70%, rgba(107, 208, 242,0.5) 100%),linear-gradient(0deg, rgb(243, 245, 245) 0%, rgb(243, 245, 245) 18%,transparent 18%, transparent 35%,transparent 35%, transparent 40%,rgb(39, 189, 241) 40%, rgb(39, 189, 241) 71%,rgb(141, 217, 243) 71%, rgb(141, 217, 243) 79%,rgb(175, 226, 244) 79%, rgb(175, 226, 244) 92%,rgb(107, 208, 242) 92%, rgb(107, 208, 242) 100%),linear-gradient(90deg, rgb(255,255,255),rgb(255,255,255))',
    group: 'Treasure',
    order: 515,
  },
  'ReadScroll10': {
    title: 'Hedgewizard',
    description: 'Read 10 scrolls...',
    image: 'items/hat/wizard',
    color: 'linear-gradient(45deg, rgba(11, 95, 67,0.5) 0%, rgba(11, 95, 67,0.5) 5%,transparent 5%, transparent 38%,transparent 38%, transparent 60%,rgba(7, 115, 73,0.5) 60%, rgba(7, 115, 73,0.5) 100%),linear-gradient(135deg, rgb(4, 136, 80) 0%, rgb(4, 136, 80) 14%,rgb(0, 156, 86) 14%, rgb(0, 156, 86) 75%,rgb(7, 115, 73) 75%, rgb(7, 115, 73) 100%),linear-gradient(90deg, rgb(255,255,255),rgb(255,255,255))',
    group: 'Treasure',
    order: 516,
  },
  'ReadScroll100': {
    title: 'Archmage',
    description: 'Read 100 scrolls!',
    image: 'items/hat/wizard',
    color: 'linear-gradient(135deg, rgba(139, 53, 123,0.5) 0%, rgba(139, 53, 123,0.5) 10%,transparent 10%, transparent 19%,rgba(84, 33, 86,0.5) 19%, rgba(84, 33, 86,0.5) 27%,rgba(157, 60, 135,0.5) 27%, rgba(157, 60, 135,0.5) 53%,transparent 53%, transparent 56%,rgba(176, 66, 147,0.5) 56%, rgba(176, 66, 147,0.5) 61%,rgba(102, 40, 98,0.5) 61%, rgba(102, 40, 98,0.5) 100%),linear-gradient(45deg, rgb(139, 53, 123) 0%, rgb(139, 53, 123) 8%,transparent 8%, transparent 9%,transparent 9%, transparent 10%,rgb(157, 60, 135) 10%, rgb(157, 60, 135) 14%,rgb(121, 46, 110) 14%, rgb(121, 46, 110) 50%,rgb(176, 66, 147) 50%, rgb(176, 66, 147) 97%,rgb(102, 40, 98) 97%, rgb(102, 40, 98) 100%),linear-gradient(90deg, rgb(255,255,255),rgb(255,255,255))',
    group: 'Treasure',
    order: 517,
  },
  'IceMangoes10': {
    title: 'Mango Violence',
    description: 'Shatter an Ice "Mango"... 10 times!',
    image: 'items/fruit/mango-ice',
    color: 'linear-gradient(to bottom right, #fff 0%, #069 100%)',
    group: 'Treasure',
    order: 518,
  },
  'Honorificabilitudinitatibus': {
    title: 'Honorificabilitudinitatibus',
    description: 'Acquire 10 Hebenon from the Trader\'s.',
    image: 'items/plant/hebenon',
    color: 'linear-gradient(green, deeppink)',
    group: 'Treasure',
    order: 519,
  },

  // Love of Boxes
  'PlazaBox1': {
    title: 'I Like Free Stuff',
    description: 'Receive a Box (or Bag) at the Plaza.',
    image: 'calendar/holidays/black-friday',
    color: '#ffffff',
    group: 'Love of Boxes',
    order: 550,
  },
  'PlazaBox10': {
    title: 'Can You Build a Box Fort with These?',
    description: 'Receive 10 Boxes (or Bags) at the Plaza...',
    image: 'items/box/new-year',
    color: '#ffffff',
    group: 'Love of Boxes',
    order: 551,
  },
  'PlazaBox100': {
    title: 'This is Too Many Boxes, Right??',
    description: 'Receive _100_ Boxes (or Bags) at the Plaza!',
    image: 'icons/activity-logs/house-too-full',
    color: '#ffffff',
    group: 'Love of Boxes',
    order: 552,
  },
  'OpenedBoxBox1': {
    title: 'Box?',
    description: 'Open a Box Box.',
    image: 'items/box/cardboard',
    color: 'radial-gradient(circle at 35% 35%, #000000 0%, #A0550D 50%, #EC933F 100%)',
    group: 'Love of Boxes',
    order: 553,
  },
  'OpenedBoxBox10': {
    title: 'Boxbox??',
    description: 'Open 10 Box Boxes.',
    image: 'items/box/cardboard',
    color: 'radial-gradient(circle at 35% 35%, #000000 0%, #EC3F3F 100%)',
    group: 'Love of Boxes',
    order: 554,
  },
  'BoxBoxBoxBox': {
    title: 'Boxboxboxboxbox?!?!',
    description: 'Find a Box Box inside a Box Box...',
    image: 'items/box/cardboard',
    color: 'radial-gradient(circle at 35% 35%, #ffffff 0%, #E4CF98 50%, #FF22F4 100%)',
    group: 'Love of Boxes',
    order: 555,
  },

  // adventure
  'DefeatedSummonedMonster1': {
    title: 'Monstrous',
    description: 'Defeat a monster you summon.',
    image: 'items/scroll/summoning',
    color: 'linear-gradient(22.5deg, #50c2bf 0%, #b1f5b4 50%, #faffac 100%)',
    group: 'Adventure',
    order: 600,
  },
  'DefeatedSummonedMonster10': {
    title: 'They Come from Outer Space',
    description: 'Defeat 10 monsters you summon.',
    image: 'items/scroll/summoning',
    color: 'linear-gradient(to top, rgb(58, 102, 171) 0%, #000 100%)',
    group: 'Adventure',
    order: 601,
  },
  'DefeatedSummonedMonster100': {
    title: 'Who\'s The Real Monster?',
    description: 'Defeat 100 monsters you summon.',
    image: 'items/scroll/summoning',
    color: 'linear-gradient(111.1deg, rgba(0,40,70,1) -4.8%, rgba(255,115,115,1) 82.7%, rgba(255,175,123,1) 97.2%)',
    group: 'Adventure',
    order: 602,
  },
  'DefeatedNoetalasWing1': {
    title: 'A Piece of Evil',
    description: 'Defeat Noetala\'s Wing.',
    image: 'items/hat/bat-wing',
    color: 'linear-gradient(-22deg, #000, #a0a)',
    group: 'Adventure',
    order: 603,
  },
  'DefeatedNoetalasWing2': {
    title: 'If It\'s Worth Doing Once...',
    description: 'Defeat Noetala\'s (other?) Wing.',
    image: 'items/hat/batling-white',
    color: 'linear-gradient(-22deg, #303, #d0d)',
    group: 'Adventure',
    order: 603.1,
  },
  'TowerOfTrials1': {
    title: 'Tower of Trials',
    description: 'Open a Tower Chest.',
    image: 'items/tool/sword/brute-force',
    color: 'linear-gradient(90deg, rgba(227,170,83,1) 0%, rgba(161,107,40,1) 100%)',
    group: 'Adventure',
    order: 604,
  },
  'TowerOfTrials10': {
    title: 'Tower of Treasures',
    description: 'Open 10 Tower Chests.',
    image: 'items/tool/sword/brute-force',
    color: 'linear-gradient(90deg, rgba(255,255,255,1) 0%, rgba(166,166,166,1) 100%)',
    group: 'Adventure',
    order: 605,
  },
  'TowerOfTrials100': {
    title: 'Tower of Triumphs',
    description: 'Open 100 Tower Chests.',
    image: 'items/tool/sword/brute-force',
    color: 'linear-gradient(90deg, rgba(255,252,0,1) 0%, rgba(253,187,45,1) 100%)',
    group: 'Adventure',
    order: 606,
  },
  'HollowEarthTravel10': {
    title: 'Boldly Going...',
    description: 'Move 10 spaces in the Hollow Earth.',
    image: 'items/die/d6',
    color: 'conic-gradient(from 112.5deg, #999, #fff, #999, #fff, #999, #fff, #999, #fff, #999)',
    group: 'Adventure',
    order: 607,
  },
  'HollowEarthTravel100': {
    title: '... Where No Pet...',
    description: 'Move 100 spaces in the Hollow Earth...',
    image: 'items/die/d10',
    color: 'conic-gradient(from 112.5deg, #fc0, #fff, #fc0, #fff, #fc0, #fff, #fc0, #fff, #fc0)',
    group: 'Adventure',
    order: 608,
  },
  'HollowEarthTravel1000': {
    title: '... Has Gone Before',
    description: 'Move 1,000 spaces in the Hollow Earth!',
    image: 'items/die/d20',
    color: 'conic-gradient(from 112.5deg, #f66, #fff, #f0f, #fff, #f66, #fff, #f0f, #fff, #f66)',
    group: 'Adventure',
    order: 609,
  },

  // great spirits
  'GreatSpiritMinorRewards1': {
    title: 'Minorly Rewarded',
    description: 'Collect 1 Minor reward from the great spirits.',
    image: 'items/treasure/magic-crystal-ball',
    color: 'conic-gradient(at 50% 80%, skyblue, white, skyblue)',
    group: 'Great Spirits',
    order: 700,
  },
  'GreatSpiritModerateRewards5': {
    title: 'Moderately Rewarded',
    description: 'Collect 5 Moderate rewards from the great spirits.',
    image: 'items/treasure/magic-crystal-ball',
    color: 'conic-gradient(at 50% 80%, gold, red, orange, white, gold)',
    group: 'Great Spirits',
    order: 701,
  },
  'GreatSpiritMajorRewards10': {
    title: 'Majorly Rewarded',
    description: 'Collect 10 Major rewards from the great spirits.',
    image: 'items/treasure/magic-crystal-ball',
    color: 'conic-gradient(at 50% 80%, purple, pink, pink, white, purple)',
    group: 'Great Spirits',
    order: 702,
  },
  'GreatSpiritHunterOfAnhur10': {
    title: 'Beautiful. Deadly.',
    description: 'Collect 10 rewards from a Hunter of Anhur.',
    image: 'monster-of-the-week/anhur',
    color: 'linear-gradient(-45deg, palegoldenrod, red,  black)',
    group: 'Great Spirits',
    order: 703,
  },
  'GreatSpiritBoshinogami10': {
    title: 'Hatshatshatshatshats',
    description: 'Collect 10 rewards from some Boshinogami.',
    image: 'monster-of-the-week/boshinogami',
    color: 'linear-gradient(white, pink, skyblue)',
    group: 'Great Spirits',
    order: 704,
  },
  'GreatSpiritCardeasLockbearer10': {
    title: 'It Watches... It Listens...',
    description: 'Collect 10 rewards from Cardea\'s Lockbearer.',
    image: 'monster-of-the-week/cardea',
    color: 'linear-gradient(black, rgb(0, 102, 153), white)',
    group: 'Great Spirits',
    order: 705,
  },
  'GreatSpiritDionysussHunger10': {
    title: 'Feast Fit for a God',
    description: 'Collect 10 rewards from Dionysus\' Hunger.',
    image: 'monster-of-the-week/dionysus',
    color: 'linear-gradient(135deg, greenyellow, green)',
    group: 'Great Spirits',
    order: 706,
  },
  'GreatSpiritHuehuecoyotlsFolly10': {
    title: 'Dancing and Belly Rubs',
    description: 'Collect 10 rewards from Huehuecoyotl\'s Folly.',
    image: 'monster-of-the-week/huehuecoyotl',
    color: 'linear-gradient(to bottom, white 0%, skyblue 50%, #069 100%)',
    group: 'Great Spirits',
    order: 707,
  },
  'GreatSpiritEiriPersona10': {
    title: 'A Shadow of a God',
    description: 'Collect 10 rewards from an Eiri Persona.',
    image: 'monster-of-the-week/eiri-persona',
    color: 'linear-gradient(#6c6 0%, #fff 100%)',
    group: 'Great Spirits',
    order: 708,
  },

  // cataloging
  'FieldGuide10': {
    title: 'Book of Plants',
    description: 'Discover 10 Field Guide entries.',
    image: 'items/book/flowers',
    color: 'skyblue',
    group: 'Cataloging',
    order: 1000,
  },
  'FieldGuide20': {
    title: 'Book of Magic',
    description: 'Discover 20 Field Guide entries.',
    image: 'items/book/broccolinomicon',
    color: '#042',
    group: 'Cataloging',
    order: 1001,
  },
  'Museum100': {
    title: 'Triple Digits',
    description: 'Donate 100 items to the Museum.',
    image: 'items/mineral/rock',
    color: MUSEUM_BRONZE_BACKGROUND,
    group: 'Cataloging',
    order: 1101,
  },
  'Museum200': {
    title: 'Collector\'s Calling',
    description: 'Donate 200 items to the Museum.',
    image: 'items/mineral/rock',
    color: MUSEUM_SILVER_BACKGROUND,
    group: 'Cataloging',
    order: 1102,
  },
  'Museum300': {
    title: 'This! Is! The Museum!',
    description: 'Donate 300 items to the Museum.',
    image: 'items/mineral/rock',
    color: MUSEUM_GOLD_BACKGROUND,
    group: 'Cataloging',
    order: 1103,
  },
  'Museum400': {
    title: 'Fantastic Four... Hundred',
    description: 'Donate 400 items to the Museum.',
    image: 'items/tool/shovel/trowel',
    color: MUSEUM_BRONZE_BACKGROUND,
    group: 'Cataloging',
    order: 1104,
  },
  'Museum500': {
    title: 'Five-star Finder',
    description: 'Donate 500 items to the Museum.',
    image: 'items/tool/shovel/trowel',
    color: MUSEUM_SILVER_BACKGROUND,
    group: 'Cataloging',
    order: 1105,
  },
  'Museum600': {
    title: 'Gatherer\'s Glee',
    description: 'Donate 600 items to the Museum.',
    image: 'items/tool/shovel/trowel',
    color: MUSEUM_GOLD_BACKGROUND,
    group: 'Cataloging',
    order: 1106,
  },
  'Museum700': {
    title: 'A Boring Number',
    description: 'Donate 700 items to the Museum.',
    image: 'items/animal/bone/stereotypical',
    color: MUSEUM_BRONZE_BACKGROUND,
    group: 'Cataloging',
    order: 1107,
  },
  'Museum800': {
    title: 'Eight Hundred\'s Great... Hundred',
    description: 'Donate 800 items to the Museum.',
    image: 'items/animal/bone/stereotypical',
    color: MUSEUM_SILVER_BACKGROUND,
    group: 'Cataloging',
    order: 1108,
  },
  'Museum900': {
    title: '30² #justmaththings',
    description: 'Donate 900 items to the Museum.',
    image: 'items/animal/bone/stereotypical',
    color: MUSEUM_GOLD_BACKGROUND,
    group: 'Cataloging',
    order: 1109,
  },
  'Museum1000': {
    title: 'Kilocollector',
    description: 'Donate 1,000 items to the Museum.',
    image: 'items/animal/bone/skull-dino',
    color: MUSEUM_BRONZE_BACKGROUND,
    group: 'Cataloging',
    order: 1110,
  },
  'Museum1100': {
    title: '12 In Binary, and In My Heart',
    description: 'Donate 1,100 items to the Museum.',
    image: 'items/animal/bone/skull-dino',
    color: MUSEUM_SILVER_BACKGROUND,
    group: 'Cataloging',
    order: 1111,
  },
  'Museum1200': {
    title: 'Surely We\'ll Go No Higher...',
    description: 'Donate 1,200 items to the Museum.',
    image: 'items/animal/bone/skull-dino',
    color: MUSEUM_GOLD_BACKGROUND,
    group: 'Cataloging',
    order: 1112,
  },
  'Zoologist10': {
    title: 'Eukaryote',
    description: 'Show 10 species to the Zoologist.',
    image: 'items/bacteria/algae',
    color: ZOOLOGIST_BRONZE_BACKGROUND,
    group: 'Cataloging',
    order: 1200,
  },
  'Zoologist20': {
    title: 'Natural Selector',
    description: 'Show 20 species to the Zoologist.',
    image: 'items/bacteria/algae',
    color: ZOOLOGIST_SILVER_BACKGROUND,
    group: 'Cataloging',
    order: 1201,
  },
  'Zoologist30': {
    title: 'Convergent Evolver',
    description: 'Show 30 species to the Zoologist.',
    image: 'items/bacteria/algae',
    color: ZOOLOGIST_GOLD_BACKGROUND,
    group: 'Cataloging',
    order: 1202,
  },
  'Zoologist40': {
    title: 'Speciator',
    description: 'Show 40 species to the Zoologist.',
    image: 'items/animal/meat/jellyfish',
    color: ZOOLOGIST_BRONZE_BACKGROUND,
    group: 'Cataloging',
    order: 1203,
  },
  'Zoologist50': {
    title: 'Genomic Imprinter',
    description: 'Show 50 species to the Zoologist.',
    image: 'items/animal/meat/jellyfish',
    color: ZOOLOGIST_SILVER_BACKGROUND,
    group: 'Cataloging',
    order: 1204,
  },
  'Zoologist60': {
    title: 'Mutator',
    description: 'Show 60 species to the Zoologist.',
    image: 'items/animal/meat/jellyfish',
    color: ZOOLOGIST_GOLD_BACKGROUND,
    group: 'Cataloging',
    order: 1205,
  },
  'Zoologist70': {
    title: 'Disruptive Selector',
    description: 'Show 70 species to the Zoologist.',
    image: 'items/animal/egg',
    color: ZOOLOGIST_BRONZE_BACKGROUND,
    group: 'Cataloging',
    order: 1206,
  },
  'Zoologist80': {
    title: 'Symbiote',
    description: 'Show 80 species to the Zoologist.',
    image: 'items/animal/egg',
    color: ZOOLOGIST_SILVER_BACKGROUND,
    group: 'Cataloging',
    order: 1207,
  },
  'Zoologist90': {
    title: 'Genetic Drifter',
    description: 'Show 90 species to the Zoologist.',
    image: 'items/animal/egg',
    color: ZOOLOGIST_GOLD_BACKGROUND,
    group: 'Cataloging',
    order: 1208,
  },
  'Zoologist100': {
    title: 'Phylogeneticist',
    description: 'Show 100 species to the Zoologist.',
    image: 'items/animal/alien-tissue',
    color: ZOOLOGIST_BRONZE_BACKGROUND,
    group: 'Cataloging',
    order: 1209,
  },

  'ApricotFestival1': {
    title: 'The Apricot Festival',
    description: 'Raid an Apricrate.',
    image: 'calendar/holidays/apricot-festival',
    color: 'skyblue',
    group: 'Event',
    order: 2000,
  },
  'ApricotFestival10': {
    title: 'Apricot Fanatic',
    description: 'Raid 10 Apricrates.',
    image: 'calendar/holidays/apricot-festival',
    color: 'yellow',
    group: 'Event',
    order: 2001,
  },

  // meta
  'AccountAge365': {
    title: 'Never Mind Leap Years',
    description: 'Have a 365-day old account.',
    image: 'items/hat/candle',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 10000,
  },
  'Achievements10': {
    title: 'Chocolate Bar',
    description: 'Claim 10 Achievements.',
    image: 'items/candy/chocolate/bar',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11000,
  },
  'Achievements20': {
    title: 'Chocolate Meringue',
    description: 'Claim 20 Achievements.',
    image: 'items/dessert/meringue-c-chip',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11001,
  },
  'Achievements30': {
    title: 'Chocolate Toffee Matzah',
    description: 'Claim 30 Achievements.',
    image: 'items/dessert/chocolate-toffee-matzah',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11002,
  },
  'Achievements40': {
    title: 'Mini Chocolate Chip Cookies',
    description: 'Claim 40 Achievements.',
    image: 'items/dessert/cookie-mini-chip',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11003,
  },
  'Achievements50': {
    title: 'Chocolate Lava Cake',
    description: 'Claim 50 Achievements.',
    image: 'items/cake/chocolate-lava',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11004,
  },
  'Achievements60': {
    title: 'Chocolate Cake Pops',
    description: 'Claim 60 Achievements.',
    image: 'items/bread/cakepops-chocolate',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11005,
  },
  'Achievements70': {
    title: 'Chocolate-covered Naner',
    description: 'Claim 70 Achievements.',
    image: 'items/dessert/naner-chocolate-covered',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11006,
  },
  'Achievements80': {
    title: 'Slice of Chocolate Cream Pie',
    description: 'Claim 80 Achievements.',
    image: 'items/dessert/pie-slice-chocolate',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11007,
  },
  'Achievements90': {
    title: 'Chocolate-frosted Donut',
    description: 'Claim 90 Achievements.',
    image: 'items/bread/donut-frosted-chocolate',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11008,
  },
  'Achievements100': {
    title: 'Chocolate Chest',
    description: 'Claim 100 Achievements.',
    image: 'items/box/chocolate-chest',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11009,
  },
  'Achievements110': {
    title: 'Chocolate Ice Cream Sammy',
    description: 'Claim 110 Achievements.',
    image: 'items/sandwich/ice-cream/chocolate-best',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11010,
  },
  'Achievements120': {
    title: 'Chocolate-covered Honeycomb',
    description: 'Claim 120 Achievements.',
    image: 'items/candy/honeycomb-chocolate-bar',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11011,
  },
  'Achievements130': {
    title: 'Chocolate Syrup',
    description: 'Claim 130 Achievements.',
    image: 'items/ingredient/chocolate-syrup',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11012,
  },
  'Achievements140': {
    title: 'Chocolate Hammer',
    description: 'Claim 140 Achievements.',
    image: 'items/tool/hammer/chocolate',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11013,
  },
  'Achievements150': {
    title: 'Scroll of Chocolate',
    description: 'Claim 150 Achievements.',
    image: 'items/scroll/chocolate',
    color: META_ACHIEVEMENT_BACKGROUND,
    group: 'Getting Meta',
    order: 11014,
  },
};

// yes, this is intentional, and expected to be seen by players:
console.log('Did you know? There are ' + Object.keys(BADGE_INFO).length + ' Achievements in Poppy Seed Pets!');
