export const EmoteFontAwesomeClasses = {
  A: 'fa-solid fa-heart',
  B: 'fa-solid fa-face-smile-hearts',
  C: 'fa-solid fa-face-smile',
  D: 'fa-solid fa-face-laugh-beam',
  E: 'fa-solid fa-music',
  F: 'fa-solid fa-dove',
  G: 'fa-solid fa-star',
  H: 'fa-solid fa-face-grin-stars',
  I: 'fa-solid fa-sparkles',
  J: 'fa-solid fa-hand-spock',
  K: 'fa-solid fa-flower-daffodil',
  L: 'fa-solid fa-flower-tulip',
  M: 'fa-solid fa-bolt',
  N: 'fa-solid fa-tree-palm',
  O: 'fa-solid fa-sunglasses',
  P: 'fa-solid fa-yin-yang',
  Q: 'fa-solid fa-cloud-rainbow',
  R: 'fa-solid fa-face-smile-upside-down',
  S: 'fa-solid fa-frog',
  T: 'fa-solid fa-face-kiss-wink-heart',
  U: 'fa-solid fa-clover',
  V: 'fa-solid fa-cat-space',
  W: 'fa-solid fa-ufo',
  X: 'fa-solid fa-strawberry',
  Y: 'fa-solid fa-rocket',
  Z: 'fa-solid fa-moon-stars',
};
